/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcRouteImport } from './routes/ac'
import { Route as AutomationRouteImport } from './routes/automation'
import { Route as BdRouteImport } from './routes/bd'
import { Route as HotelProfileRouteImport } from './routes/hotel-profile'
import { Route as HrRouteImport } from './routes/hr'
import { Route as MarcomRouteImport } from './routes/marcom'
import { Route as OrmRouteImport } from './routes/orm'
import { Route as PsRouteImport } from './routes/ps'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SystemCostRouteImport } from './routes/system-cost'
import { Route as AcIndexRouteImport } from './routes/ac.index'
import { Route as AcBillingRouteImport } from './routes/ac.billing'
import { Route as AcCustomersRouteImport } from './routes/ac.customers'
import { Route as AcHotelProfileRouteImport } from './routes/ac.hotel-profile'
import { Route as AcProductsRouteImport } from './routes/ac.products'
import { Route as AcSystemCostRouteImport } from './routes/ac.system-cost'
import { Route as BdIndexRouteImport } from './routes/bd.index'
import { Route as BdCalculatorRouteImport } from './routes/bd.calculator'
import { Route as BdDealsRouteImport } from './routes/bd.deals'
import { Route as BdQuotationsRouteImport } from './routes/bd.quotations'
import { Route as BdQuotesRouteImport } from './routes/bd.quotes'
import { Route as BdRegisterDealRouteImport } from './routes/bd.register-deal'
import { Route as LTokenRouteImport } from './routes/l.$token'
import { Route as PsIndexRouteImport } from './routes/ps.index'
import { Route as PsContractDashboardRouteImport } from './routes/ps.contract-dashboard'
import { Route as PsContractWizardRouteImport } from './routes/ps.contract-wizard'
import { Route as PsContractsRouteImport } from './routes/ps.contracts'
import { Route as PsProductionRouteImport } from './routes/ps.production'
import { Route as PsSystemCostRouteImport } from './routes/ps.system-cost'
import { Route as BdCalculatorMarcomRouteImport } from './routes/bd.calculator.marcom'
import { Route as BdCalculatorOrmRouteImport } from './routes/bd.calculator.orm'
import { Route as BdQuotationsIndexRouteImport } from './routes/bd.quotations.index'
import { Route as BdQuotationsQuoteIdRouteImport } from './routes/bd.quotations.$quoteId'
import { Route as BdQuotesIndexRouteImport } from './routes/bd.quotes.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcRoute = AcRouteImport.update({
  id: '/ac',
  path: '/ac',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRoute = AutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const BdRoute = BdRouteImport.update({
  id: '/bd',
  path: '/bd',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelProfileRoute = HotelProfileRouteImport.update({
  id: '/hotel-profile',
  path: '/hotel-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const HrRoute = HrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcomRoute = MarcomRouteImport.update({
  id: '/marcom',
  path: '/marcom',
  getParentRoute: () => rootRouteImport,
} as any)
const OrmRoute = OrmRouteImport.update({
  id: '/orm',
  path: '/orm',
  getParentRoute: () => rootRouteImport,
} as any)
const PsRoute = PsRouteImport.update({
  id: '/ps',
  path: '/ps',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemCostRoute = SystemCostRouteImport.update({
  id: '/system-cost',
  path: '/system-cost',
  getParentRoute: () => rootRouteImport,
} as any)
const AcIndexRoute = AcIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AcRoute,
} as any)
const AcBillingRoute = AcBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AcRoute,
} as any)
const AcCustomersRoute = AcCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AcRoute,
} as any)
const AcHotelProfileRoute = AcHotelProfileRouteImport.update({
  id: '/hotel-profile',
  path: '/hotel-profile',
  getParentRoute: () => AcRoute,
} as any)
const AcProductsRoute = AcProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AcRoute,
} as any)
const AcSystemCostRoute = AcSystemCostRouteImport.update({
  id: '/system-cost',
  path: '/system-cost',
  getParentRoute: () => AcRoute,
} as any)
const BdIndexRoute = BdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BdRoute,
} as any)
const BdCalculatorRoute = BdCalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => BdRoute,
} as any)
const BdDealsRoute = BdDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => BdRoute,
} as any)
const BdQuotationsRoute = BdQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => BdRoute,
} as any)
const BdQuotesRoute = BdQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => BdRoute,
} as any)
const BdRegisterDealRoute = BdRegisterDealRouteImport.update({
  id: '/register-deal',
  path: '/register-deal',
  getParentRoute: () => BdRoute,
} as any)
const LTokenRoute = LTokenRouteImport.update({
  id: '/l/$token',
  path: '/l/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PsIndexRoute = PsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PsRoute,
} as any)
const PsContractDashboardRoute = PsContractDashboardRouteImport.update({
  id: '/contract-dashboard',
  path: '/contract-dashboard',
  getParentRoute: () => PsRoute,
} as any)
const PsContractWizardRoute = PsContractWizardRouteImport.update({
  id: '/contract-wizard',
  path: '/contract-wizard',
  getParentRoute: () => PsRoute,
} as any)
const PsContractsRoute = PsContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => PsRoute,
} as any)
const PsProductionRoute = PsProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => PsRoute,
} as any)
const PsSystemCostRoute = PsSystemCostRouteImport.update({
  id: '/system-cost',
  path: '/system-cost',
  getParentRoute: () => PsRoute,
} as any)
const BdCalculatorMarcomRoute = BdCalculatorMarcomRouteImport.update({
  id: '/marcom',
  path: '/marcom',
  getParentRoute: () => BdCalculatorRoute,
} as any)
const BdCalculatorOrmRoute = BdCalculatorOrmRouteImport.update({
  id: '/orm',
  path: '/orm',
  getParentRoute: () => BdCalculatorRoute,
} as any)
const BdQuotationsIndexRoute = BdQuotationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BdQuotationsRoute,
} as any)
const BdQuotationsQuoteIdRoute = BdQuotationsQuoteIdRouteImport.update({
  id: '/$quoteId',
  path: '/$quoteId',
  getParentRoute: () => BdQuotationsRoute,
} as any)
const BdQuotesIndexRoute = BdQuotesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BdQuotesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ac': typeof AcRouteWithChildren
  '/automation': typeof AutomationRoute
  '/bd': typeof BdRouteWithChildren
  '/hotel-profile': typeof HotelProfileRoute
  '/hr': typeof HrRoute
  '/marcom': typeof MarcomRoute
  '/orm': typeof OrmRoute
  '/ps': typeof PsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/system-cost': typeof SystemCostRoute
  '/ac/billing': typeof AcBillingRoute
  '/ac/customers': typeof AcCustomersRoute
  '/ac/hotel-profile': typeof AcHotelProfileRoute
  '/ac/products': typeof AcProductsRoute
  '/ac/system-cost': typeof AcSystemCostRoute
  '/bd/calculator': typeof BdCalculatorRouteWithChildren
  '/bd/deals': typeof BdDealsRoute
  '/bd/quotations': typeof BdQuotationsRouteWithChildren
  '/bd/quotes': typeof BdQuotesRouteWithChildren
  '/bd/register-deal': typeof BdRegisterDealRoute
  '/l/$token': typeof LTokenRoute
  '/ps/contract-dashboard': typeof PsContractDashboardRoute
  '/ps/contract-wizard': typeof PsContractWizardRoute
  '/ps/contracts': typeof PsContractsRoute
  '/ps/production': typeof PsProductionRoute
  '/ps/system-cost': typeof PsSystemCostRoute
  '/ac/': typeof AcIndexRoute
  '/bd/': typeof BdIndexRoute
  '/ps/': typeof PsIndexRoute
  '/bd/calculator/marcom': typeof BdCalculatorMarcomRoute
  '/bd/calculator/orm': typeof BdCalculatorOrmRoute
  '/bd/quotations/$quoteId': typeof BdQuotationsQuoteIdRoute
  '/bd/quotations/': typeof BdQuotationsIndexRoute
  '/bd/quotes/': typeof BdQuotesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/automation': typeof AutomationRoute
  '/hotel-profile': typeof HotelProfileRoute
  '/hr': typeof HrRoute
  '/marcom': typeof MarcomRoute
  '/orm': typeof OrmRoute
  '/settings': typeof SettingsRoute
  '/system-cost': typeof SystemCostRoute
  '/ac/billing': typeof AcBillingRoute
  '/ac/customers': typeof AcCustomersRoute
  '/ac/hotel-profile': typeof AcHotelProfileRoute
  '/ac/products': typeof AcProductsRoute
  '/ac/system-cost': typeof AcSystemCostRoute
  '/bd/calculator': typeof BdCalculatorRouteWithChildren
  '/bd/deals': typeof BdDealsRoute
  '/bd/register-deal': typeof BdRegisterDealRoute
  '/l/$token': typeof LTokenRoute
  '/ps/contract-dashboard': typeof PsContractDashboardRoute
  '/ps/contract-wizard': typeof PsContractWizardRoute
  '/ps/contracts': typeof PsContractsRoute
  '/ps/production': typeof PsProductionRoute
  '/ps/system-cost': typeof PsSystemCostRoute
  '/ac': typeof AcIndexRoute
  '/bd': typeof BdIndexRoute
  '/ps': typeof PsIndexRoute
  '/bd/calculator/marcom': typeof BdCalculatorMarcomRoute
  '/bd/calculator/orm': typeof BdCalculatorOrmRoute
  '/bd/quotations/$quoteId': typeof BdQuotationsQuoteIdRoute
  '/bd/quotations': typeof BdQuotationsIndexRoute
  '/bd/quotes': typeof BdQuotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ac': typeof AcRouteWithChildren
  '/automation': typeof AutomationRoute
  '/bd': typeof BdRouteWithChildren
  '/hotel-profile': typeof HotelProfileRoute
  '/hr': typeof HrRoute
  '/marcom': typeof MarcomRoute
  '/orm': typeof OrmRoute
  '/ps': typeof PsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/system-cost': typeof SystemCostRoute
  '/ac/billing': typeof AcBillingRoute
  '/ac/customers': typeof AcCustomersRoute
  '/ac/hotel-profile': typeof AcHotelProfileRoute
  '/ac/products': typeof AcProductsRoute
  '/ac/system-cost': typeof AcSystemCostRoute
  '/bd/calculator': typeof BdCalculatorRouteWithChildren
  '/bd/deals': typeof BdDealsRoute
  '/bd/quotations': typeof BdQuotationsRouteWithChildren
  '/bd/quotes': typeof BdQuotesRouteWithChildren
  '/bd/register-deal': typeof BdRegisterDealRoute
  '/l/$token': typeof LTokenRoute
  '/ps/contract-dashboard': typeof PsContractDashboardRoute
  '/ps/contract-wizard': typeof PsContractWizardRoute
  '/ps/contracts': typeof PsContractsRoute
  '/ps/production': typeof PsProductionRoute
  '/ps/system-cost': typeof PsSystemCostRoute
  '/ac/': typeof AcIndexRoute
  '/bd/': typeof BdIndexRoute
  '/ps/': typeof PsIndexRoute
  '/bd/calculator/marcom': typeof BdCalculatorMarcomRoute
  '/bd/calculator/orm': typeof BdCalculatorOrmRoute
  '/bd/quotations/$quoteId': typeof BdQuotationsQuoteIdRoute
  '/bd/quotations/': typeof BdQuotationsIndexRoute
  '/bd/quotes/': typeof BdQuotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ac'
    | '/automation'
    | '/bd'
    | '/hotel-profile'
    | '/hr'
    | '/marcom'
    | '/orm'
    | '/ps'
    | '/settings'
    | '/system-cost'
    | '/ac/billing'
    | '/ac/customers'
    | '/ac/hotel-profile'
    | '/ac/products'
    | '/ac/system-cost'
    | '/bd/calculator'
    | '/bd/deals'
    | '/bd/quotations'
    | '/bd/quotes'
    | '/bd/register-deal'
    | '/l/$token'
    | '/ps/contract-dashboard'
    | '/ps/contract-wizard'
    | '/ps/contracts'
    | '/ps/production'
    | '/ps/system-cost'
    | '/ac/'
    | '/bd/'
    | '/ps/'
    | '/bd/calculator/marcom'
    | '/bd/calculator/orm'
    | '/bd/quotations/$quoteId'
    | '/bd/quotations/'
    | '/bd/quotes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/automation'
    | '/hotel-profile'
    | '/hr'
    | '/marcom'
    | '/orm'
    | '/settings'
    | '/system-cost'
    | '/ac/billing'
    | '/ac/customers'
    | '/ac/hotel-profile'
    | '/ac/products'
    | '/ac/system-cost'
    | '/bd/calculator'
    | '/bd/deals'
    | '/bd/register-deal'
    | '/l/$token'
    | '/ps/contract-dashboard'
    | '/ps/contract-wizard'
    | '/ps/contracts'
    | '/ps/production'
    | '/ps/system-cost'
    | '/ac'
    | '/bd'
    | '/ps'
    | '/bd/calculator/marcom'
    | '/bd/calculator/orm'
    | '/bd/quotations/$quoteId'
    | '/bd/quotations'
    | '/bd/quotes'
  id:
    | '__root__'
    | '/'
    | '/ac'
    | '/automation'
    | '/bd'
    | '/hotel-profile'
    | '/hr'
    | '/marcom'
    | '/orm'
    | '/ps'
    | '/settings'
    | '/system-cost'
    | '/ac/billing'
    | '/ac/customers'
    | '/ac/hotel-profile'
    | '/ac/products'
    | '/ac/system-cost'
    | '/bd/calculator'
    | '/bd/deals'
    | '/bd/quotations'
    | '/bd/quotes'
    | '/bd/register-deal'
    | '/l/$token'
    | '/ps/contract-dashboard'
    | '/ps/contract-wizard'
    | '/ps/contracts'
    | '/ps/production'
    | '/ps/system-cost'
    | '/ac/'
    | '/bd/'
    | '/ps/'
    | '/bd/calculator/marcom'
    | '/bd/calculator/orm'
    | '/bd/quotations/$quoteId'
    | '/bd/quotations/'
    | '/bd/quotes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcRoute: typeof AcRouteWithChildren
  AutomationRoute: typeof AutomationRoute
  BdRoute: typeof BdRouteWithChildren
  HotelProfileRoute: typeof HotelProfileRoute
  HrRoute: typeof HrRoute
  MarcomRoute: typeof MarcomRoute
  OrmRoute: typeof OrmRoute
  PsRoute: typeof PsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SystemCostRoute: typeof SystemCostRoute
  LTokenRoute: typeof LTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ac': {
      id: '/ac'
      path: '/ac'
      fullPath: '/ac'
      preLoaderRoute: typeof AcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation': {
      id: '/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bd': {
      id: '/bd'
      path: '/bd'
      fullPath: '/bd'
      preLoaderRoute: typeof BdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel-profile': {
      id: '/hotel-profile'
      path: '/hotel-profile'
      fullPath: '/hotel-profile'
      preLoaderRoute: typeof HotelProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr': {
      id: '/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof HrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marcom': {
      id: '/marcom'
      path: '/marcom'
      fullPath: '/marcom'
      preLoaderRoute: typeof MarcomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orm': {
      id: '/orm'
      path: '/orm'
      fullPath: '/orm'
      preLoaderRoute: typeof OrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ps': {
      id: '/ps'
      path: '/ps'
      fullPath: '/ps'
      preLoaderRoute: typeof PsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-cost': {
      id: '/system-cost'
      path: '/system-cost'
      fullPath: '/system-cost'
      preLoaderRoute: typeof SystemCostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ac/': {
      id: '/ac/'
      path: '/'
      fullPath: '/ac/'
      preLoaderRoute: typeof AcIndexRouteImport
      parentRoute: typeof AcRoute
    }
    '/ac/billing': {
      id: '/ac/billing'
      path: '/billing'
      fullPath: '/ac/billing'
      preLoaderRoute: typeof AcBillingRouteImport
      parentRoute: typeof AcRoute
    }
    '/ac/customers': {
      id: '/ac/customers'
      path: '/customers'
      fullPath: '/ac/customers'
      preLoaderRoute: typeof AcCustomersRouteImport
      parentRoute: typeof AcRoute
    }
    '/ac/hotel-profile': {
      id: '/ac/hotel-profile'
      path: '/hotel-profile'
      fullPath: '/ac/hotel-profile'
      preLoaderRoute: typeof AcHotelProfileRouteImport
      parentRoute: typeof AcRoute
    }
    '/ac/products': {
      id: '/ac/products'
      path: '/products'
      fullPath: '/ac/products'
      preLoaderRoute: typeof AcProductsRouteImport
      parentRoute: typeof AcRoute
    }
    '/ac/system-cost': {
      id: '/ac/system-cost'
      path: '/system-cost'
      fullPath: '/ac/system-cost'
      preLoaderRoute: typeof AcSystemCostRouteImport
      parentRoute: typeof AcRoute
    }
    '/bd/': {
      id: '/bd/'
      path: '/'
      fullPath: '/bd/'
      preLoaderRoute: typeof BdIndexRouteImport
      parentRoute: typeof BdRoute
    }
    '/bd/calculator': {
      id: '/bd/calculator'
      path: '/calculator'
      fullPath: '/bd/calculator'
      preLoaderRoute: typeof BdCalculatorRouteImport
      parentRoute: typeof BdRoute
    }
    '/bd/deals': {
      id: '/bd/deals'
      path: '/deals'
      fullPath: '/bd/deals'
      preLoaderRoute: typeof BdDealsRouteImport
      parentRoute: typeof BdRoute
    }
    '/bd/quotations': {
      id: '/bd/quotations'
      path: '/quotations'
      fullPath: '/bd/quotations'
      preLoaderRoute: typeof BdQuotationsRouteImport
      parentRoute: typeof BdRoute
    }
    '/bd/quotes': {
      id: '/bd/quotes'
      path: '/quotes'
      fullPath: '/bd/quotes'
      preLoaderRoute: typeof BdQuotesRouteImport
      parentRoute: typeof BdRoute
    }
    '/bd/register-deal': {
      id: '/bd/register-deal'
      path: '/register-deal'
      fullPath: '/bd/register-deal'
      preLoaderRoute: typeof BdRegisterDealRouteImport
      parentRoute: typeof BdRoute
    }
    '/l/$token': {
      id: '/l/$token'
      path: '/l/$token'
      fullPath: '/l/$token'
      preLoaderRoute: typeof LTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ps/': {
      id: '/ps/'
      path: '/'
      fullPath: '/ps/'
      preLoaderRoute: typeof PsIndexRouteImport
      parentRoute: typeof PsRoute
    }
    '/ps/contract-dashboard': {
      id: '/ps/contract-dashboard'
      path: '/contract-dashboard'
      fullPath: '/ps/contract-dashboard'
      preLoaderRoute: typeof PsContractDashboardRouteImport
      parentRoute: typeof PsRoute
    }
    '/ps/contract-wizard': {
      id: '/ps/contract-wizard'
      path: '/contract-wizard'
      fullPath: '/ps/contract-wizard'
      preLoaderRoute: typeof PsContractWizardRouteImport
      parentRoute: typeof PsRoute
    }
    '/ps/contracts': {
      id: '/ps/contracts'
      path: '/contracts'
      fullPath: '/ps/contracts'
      preLoaderRoute: typeof PsContractsRouteImport
      parentRoute: typeof PsRoute
    }
    '/ps/production': {
      id: '/ps/production'
      path: '/production'
      fullPath: '/ps/production'
      preLoaderRoute: typeof PsProductionRouteImport
      parentRoute: typeof PsRoute
    }
    '/ps/system-cost': {
      id: '/ps/system-cost'
      path: '/system-cost'
      fullPath: '/ps/system-cost'
      preLoaderRoute: typeof PsSystemCostRouteImport
      parentRoute: typeof PsRoute
    }
    '/bd/calculator/marcom': {
      id: '/bd/calculator/marcom'
      path: '/marcom'
      fullPath: '/bd/calculator/marcom'
      preLoaderRoute: typeof BdCalculatorMarcomRouteImport
      parentRoute: typeof BdCalculatorRoute
    }
    '/bd/calculator/orm': {
      id: '/bd/calculator/orm'
      path: '/orm'
      fullPath: '/bd/calculator/orm'
      preLoaderRoute: typeof BdCalculatorOrmRouteImport
      parentRoute: typeof BdCalculatorRoute
    }
    '/bd/quotations/': {
      id: '/bd/quotations/'
      path: '/'
      fullPath: '/bd/quotations/'
      preLoaderRoute: typeof BdQuotationsIndexRouteImport
      parentRoute: typeof BdQuotationsRoute
    }
    '/bd/quotations/$quoteId': {
      id: '/bd/quotations/$quoteId'
      path: '/$quoteId'
      fullPath: '/bd/quotations/$quoteId'
      preLoaderRoute: typeof BdQuotationsQuoteIdRouteImport
      parentRoute: typeof BdQuotationsRoute
    }
    '/bd/quotes/': {
      id: '/bd/quotes/'
      path: '/'
      fullPath: '/bd/quotes/'
      preLoaderRoute: typeof BdQuotesIndexRouteImport
      parentRoute: typeof BdQuotesRoute
    }
  }
}

interface AcRouteChildren {
  AcBillingRoute: typeof AcBillingRoute
  AcCustomersRoute: typeof AcCustomersRoute
  AcHotelProfileRoute: typeof AcHotelProfileRoute
  AcProductsRoute: typeof AcProductsRoute
  AcSystemCostRoute: typeof AcSystemCostRoute
  AcIndexRoute: typeof AcIndexRoute
}

const AcRouteChildren: AcRouteChildren = {
  AcBillingRoute: AcBillingRoute,
  AcCustomersRoute: AcCustomersRoute,
  AcHotelProfileRoute: AcHotelProfileRoute,
  AcProductsRoute: AcProductsRoute,
  AcSystemCostRoute: AcSystemCostRoute,
  AcIndexRoute: AcIndexRoute,
}

const AcRouteWithChildren = AcRoute._addFileChildren(AcRouteChildren)

interface BdCalculatorRouteChildren {
  BdCalculatorMarcomRoute: typeof BdCalculatorMarcomRoute
  BdCalculatorOrmRoute: typeof BdCalculatorOrmRoute
}

const BdCalculatorRouteChildren: BdCalculatorRouteChildren = {
  BdCalculatorMarcomRoute: BdCalculatorMarcomRoute,
  BdCalculatorOrmRoute: BdCalculatorOrmRoute,
}

const BdCalculatorRouteWithChildren = BdCalculatorRoute._addFileChildren(
  BdCalculatorRouteChildren,
)

interface BdQuotationsRouteChildren {
  BdQuotationsQuoteIdRoute: typeof BdQuotationsQuoteIdRoute
  BdQuotationsIndexRoute: typeof BdQuotationsIndexRoute
}

const BdQuotationsRouteChildren: BdQuotationsRouteChildren = {
  BdQuotationsQuoteIdRoute: BdQuotationsQuoteIdRoute,
  BdQuotationsIndexRoute: BdQuotationsIndexRoute,
}

const BdQuotationsRouteWithChildren = BdQuotationsRoute._addFileChildren(
  BdQuotationsRouteChildren,
)

interface BdQuotesRouteChildren {
  BdQuotesIndexRoute: typeof BdQuotesIndexRoute
}

const BdQuotesRouteChildren: BdQuotesRouteChildren = {
  BdQuotesIndexRoute: BdQuotesIndexRoute,
}

const BdQuotesRouteWithChildren = BdQuotesRoute._addFileChildren(
  BdQuotesRouteChildren,
)

interface BdRouteChildren {
  BdCalculatorRoute: typeof BdCalculatorRouteWithChildren
  BdDealsRoute: typeof BdDealsRoute
  BdQuotationsRoute: typeof BdQuotationsRouteWithChildren
  BdQuotesRoute: typeof BdQuotesRouteWithChildren
  BdRegisterDealRoute: typeof BdRegisterDealRoute
  BdIndexRoute: typeof BdIndexRoute
}

const BdRouteChildren: BdRouteChildren = {
  BdCalculatorRoute: BdCalculatorRouteWithChildren,
  BdDealsRoute: BdDealsRoute,
  BdQuotationsRoute: BdQuotationsRouteWithChildren,
  BdQuotesRoute: BdQuotesRouteWithChildren,
  BdRegisterDealRoute: BdRegisterDealRoute,
  BdIndexRoute: BdIndexRoute,
}

const BdRouteWithChildren = BdRoute._addFileChildren(BdRouteChildren)

interface PsRouteChildren {
  PsContractDashboardRoute: typeof PsContractDashboardRoute
  PsContractWizardRoute: typeof PsContractWizardRoute
  PsContractsRoute: typeof PsContractsRoute
  PsProductionRoute: typeof PsProductionRoute
  PsSystemCostRoute: typeof PsSystemCostRoute
  PsIndexRoute: typeof PsIndexRoute
}

const PsRouteChildren: PsRouteChildren = {
  PsContractDashboardRoute: PsContractDashboardRoute,
  PsContractWizardRoute: PsContractWizardRoute,
  PsContractsRoute: PsContractsRoute,
  PsProductionRoute: PsProductionRoute,
  PsSystemCostRoute: PsSystemCostRoute,
  PsIndexRoute: PsIndexRoute,
}

const PsRouteWithChildren = PsRoute._addFileChildren(PsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcRoute: AcRouteWithChildren,
  AutomationRoute: AutomationRoute,
  BdRoute: BdRouteWithChildren,
  HotelProfileRoute: HotelProfileRoute,
  HrRoute: HrRoute,
  MarcomRoute: MarcomRoute,
  OrmRoute: OrmRoute,
  PsRoute: PsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SystemCostRoute: SystemCostRoute,
  LTokenRoute: LTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
