/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcRouteImport } from './routes/ac'
import { Route as AutomationRouteImport } from './routes/automation'
import { Route as BdRouteImport } from './routes/bd'
import { Route as HotelProfileRouteImport } from './routes/hotel-profile'
import { Route as HrRouteImport } from './routes/hr'
import { Route as MarcomRouteImport } from './routes/marcom'
import { Route as OrmRouteImport } from './routes/orm'
import { Route as PsRouteImport } from './routes/ps'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SystemCostRouteImport } from './routes/system-cost'
import { Route as TheOfficeAppRouteImport } from './routes/the-office-app'
import { Route as AcIndexRouteImport } from './routes/ac.index'
import { Route as AcBillingRouteImport } from './routes/ac.billing'
import { Route as AcCustomersRouteImport } from './routes/ac.customers'
import { Route as AcHotelProfileRouteImport } from './routes/ac.hotel-profile'
import { Route as AcProductsRouteImport } from './routes/ac.products'
import { Route as AcSystemCostRouteImport } from './routes/ac.system-cost'
import { Route as BdIndexRouteImport } from './routes/bd.index'
import { Route as BdCalculatorRouteImport } from './routes/bd.calculator'
import { Route as BdDealsRouteImport } from './routes/bd.deals'
import { Route as BdQuotationsRouteImport } from './routes/bd.quotations'
import { Route as BdQuotesRouteImport } from './routes/bd.quotes'
import { Route as BdRegisterDealRouteImport } from './routes/bd.register-deal'
import { Route as LTokenRouteImport } from './routes/l.$token'
import { Route as OrmIndexRouteImport } from './routes/orm.index'
import { Route as OrmActionARouteImport } from './routes/orm.action-a'
import { Route as PsIndexRouteImport } from './routes/ps.index'
import { Route as PsAeWorkspaceRouteImport } from './routes/ps.ae-workspace'
import { Route as PsContractDashboardRouteImport } from './routes/ps.contract-dashboard'
import { Route as PsContractWizardRouteImport } from './routes/ps.contract-wizard'
import { Route as PsContractsRouteImport } from './routes/ps.contracts'
import { Route as PsOnboardingProcessRouteImport } from './routes/ps.onboarding-process'
import { Route as PsProductionRouteImport } from './routes/ps.production'
import { Route as PsSystemCostRouteImport } from './routes/ps.system-cost'
import { Route as TheOfficeAppIndexRouteImport } from './routes/the-office-app.index'
import { Route as TheOfficeAppOrmBonusRouteImport } from './routes/the-office-app.orm-bonus'
import { Route as BdCalculatorMarcomRouteImport } from './routes/bd.calculator.marcom'
import { Route as BdCalculatorOrmRouteImport } from './routes/bd.calculator.orm'
import { Route as BdQuotationsIndexRouteImport } from './routes/bd.quotations.index'
import { Route as BdQuotationsQuoteIdRouteImport } from './routes/bd.quotations.$quoteId'
import { Route as BdQuotesIndexRouteImport } from './routes/bd.quotes.index'
import { Route as BdQuotesQuoteIdRouteImport } from './routes/bd.quotes.$quoteId'
import { Route as BdQuotesLifecycleRouteImport } from './routes/bd.quotes.lifecycle'
import { Route as OrmActionAIndexRouteImport } from './routes/orm.action-a.index'
import { Route as OrmActionAAnalysisRouteImport } from './routes/orm.action-a.analysis'
import { Route as OrmActionAReportRouteImport } from './routes/orm.action-a.report'
import { Route as OrmActionAReviewRouteImport } from './routes/orm.action-a.review'
import { Route as OrmActionASettingsRouteImport } from './routes/orm.action-a.settings'
import { Route as PsAeWorkspaceIndexRouteImport } from './routes/ps.ae-workspace.index'
import { Route as PsAeWorkspaceCalendarRouteImport } from './routes/ps.ae-workspace.calendar'
import { Route as PsAeWorkspaceCoachingRouteImport } from './routes/ps.ae-workspace.coaching'
import { Route as PsAeWorkspaceDashboardRouteImport } from './routes/ps.ae-workspace.dashboard'
import { Route as PsAeWorkspaceMeetingsRouteImport } from './routes/ps.ae-workspace.meetings'
import { Route as PsAeWorkspaceMyTasksRouteImport } from './routes/ps.ae-workspace.my-tasks'
import { Route as PsAeWorkspacePropertyInfoRouteImport } from './routes/ps.ae-workspace.property-info'
import { Route as PsAeWorkspaceSurveysRouteImport } from './routes/ps.ae-workspace.surveys'
import { Route as PsContractWizardIndexRouteImport } from './routes/ps.contract-wizard.index'
import { Route as PsContractWizardDealIdRouteImport } from './routes/ps.contract-wizard.$dealId'
import { Route as PsContractWizardClassicRouteImport } from './routes/ps.contract-wizard.classic'
import { Route as PsContractWizardNewRouteImport } from './routes/ps.contract-wizard.new'
import { Route as PsTemplatesIndexRouteImport } from './routes/ps.templates.index'
import { Route as PsTemplatesTemplateIdRouteImport } from './routes/ps.templates.$templateId'
import { Route as PsTemplatesAutoFieldsRouteImport } from './routes/ps.templates.auto-fields'
import { Route as PsTemplatesBlockGroupsGroupIdRouteImport } from './routes/ps.templates.block-groups.$groupId'
import { Route as PsTemplatesPreviewTemplateIdRouteImport } from './routes/ps.templates.preview.$templateId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcRoute = AcRouteImport.update({
  id: '/ac',
  path: '/ac',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRoute = AutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const BdRoute = BdRouteImport.update({
  id: '/bd',
  path: '/bd',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelProfileRoute = HotelProfileRouteImport.update({
  id: '/hotel-profile',
  path: '/hotel-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const HrRoute = HrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcomRoute = MarcomRouteImport.update({
  id: '/marcom',
  path: '/marcom',
  getParentRoute: () => rootRouteImport,
} as any)
const OrmRoute = OrmRouteImport.update({
  id: '/orm',
  path: '/orm',
  getParentRoute: () => rootRouteImport,
} as any)
const PsRoute = PsRouteImport.update({
  id: '/ps',
  path: '/ps',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemCostRoute = SystemCostRouteImport.update({
  id: '/system-cost',
  path: '/system-cost',
  getParentRoute: () => rootRouteImport,
} as any)
const TheOfficeAppRoute = TheOfficeAppRouteImport.update({
  id: '/the-office-app',
  path: '/the-office-app',
  getParentRoute: () => rootRouteImport,
} as any)
const AcIndexRoute = AcIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AcRoute,
} as any)
const AcBillingRoute = AcBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AcRoute,
} as any)
const AcCustomersRoute = AcCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AcRoute,
} as any)
const AcHotelProfileRoute = AcHotelProfileRouteImport.update({
  id: '/hotel-profile',
  path: '/hotel-profile',
  getParentRoute: () => AcRoute,
} as any)
const AcProductsRoute = AcProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AcRoute,
} as any)
const AcSystemCostRoute = AcSystemCostRouteImport.update({
  id: '/system-cost',
  path: '/system-cost',
  getParentRoute: () => AcRoute,
} as any)
const BdIndexRoute = BdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BdRoute,
} as any)
const BdCalculatorRoute = BdCalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => BdRoute,
} as any)
const BdDealsRoute = BdDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => BdRoute,
} as any)
const BdQuotationsRoute = BdQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => BdRoute,
} as any)
const BdQuotesRoute = BdQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => BdRoute,
} as any)
const BdRegisterDealRoute = BdRegisterDealRouteImport.update({
  id: '/register-deal',
  path: '/register-deal',
  getParentRoute: () => BdRoute,
} as any)
const LTokenRoute = LTokenRouteImport.update({
  id: '/l/$token',
  path: '/l/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const OrmIndexRoute = OrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrmRoute,
} as any)
const OrmActionARoute = OrmActionARouteImport.update({
  id: '/action-a',
  path: '/action-a',
  getParentRoute: () => OrmRoute,
} as any)
const PsIndexRoute = PsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PsRoute,
} as any)
const PsAeWorkspaceRoute = PsAeWorkspaceRouteImport.update({
  id: '/ae-workspace',
  path: '/ae-workspace',
  getParentRoute: () => PsRoute,
} as any)
const PsContractDashboardRoute = PsContractDashboardRouteImport.update({
  id: '/contract-dashboard',
  path: '/contract-dashboard',
  getParentRoute: () => PsRoute,
} as any)
const PsContractWizardRoute = PsContractWizardRouteImport.update({
  id: '/contract-wizard',
  path: '/contract-wizard',
  getParentRoute: () => PsRoute,
} as any)
const PsContractsRoute = PsContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => PsRoute,
} as any)
const PsOnboardingProcessRoute = PsOnboardingProcessRouteImport.update({
  id: '/onboarding-process',
  path: '/onboarding-process',
  getParentRoute: () => PsRoute,
} as any)
const PsProductionRoute = PsProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => PsRoute,
} as any)
const PsSystemCostRoute = PsSystemCostRouteImport.update({
  id: '/system-cost',
  path: '/system-cost',
  getParentRoute: () => PsRoute,
} as any)
const TheOfficeAppIndexRoute = TheOfficeAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TheOfficeAppRoute,
} as any)
const TheOfficeAppOrmBonusRoute = TheOfficeAppOrmBonusRouteImport.update({
  id: '/orm-bonus',
  path: '/orm-bonus',
  getParentRoute: () => TheOfficeAppRoute,
} as any)
const BdCalculatorMarcomRoute = BdCalculatorMarcomRouteImport.update({
  id: '/marcom',
  path: '/marcom',
  getParentRoute: () => BdCalculatorRoute,
} as any)
const BdCalculatorOrmRoute = BdCalculatorOrmRouteImport.update({
  id: '/orm',
  path: '/orm',
  getParentRoute: () => BdCalculatorRoute,
} as any)
const BdQuotationsIndexRoute = BdQuotationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BdQuotationsRoute,
} as any)
const BdQuotationsQuoteIdRoute = BdQuotationsQuoteIdRouteImport.update({
  id: '/$quoteId',
  path: '/$quoteId',
  getParentRoute: () => BdQuotationsRoute,
} as any)
const BdQuotesIndexRoute = BdQuotesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BdQuotesRoute,
} as any)
const BdQuotesQuoteIdRoute = BdQuotesQuoteIdRouteImport.update({
  id: '/$quoteId',
  path: '/$quoteId',
  getParentRoute: () => BdQuotesRoute,
} as any)
const BdQuotesLifecycleRoute = BdQuotesLifecycleRouteImport.update({
  id: '/lifecycle',
  path: '/lifecycle',
  getParentRoute: () => BdQuotesRoute,
} as any)
const OrmActionAIndexRoute = OrmActionAIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrmActionARoute,
} as any)
const OrmActionAAnalysisRoute = OrmActionAAnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => OrmActionARoute,
} as any)
const OrmActionAReportRoute = OrmActionAReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => OrmActionARoute,
} as any)
const OrmActionAReviewRoute = OrmActionAReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => OrmActionARoute,
} as any)
const OrmActionASettingsRoute = OrmActionASettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OrmActionARoute,
} as any)
const PsAeWorkspaceIndexRoute = PsAeWorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PsAeWorkspaceRoute,
} as any)
const PsAeWorkspaceCalendarRoute = PsAeWorkspaceCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => PsAeWorkspaceRoute,
} as any)
const PsAeWorkspaceCoachingRoute = PsAeWorkspaceCoachingRouteImport.update({
  id: '/coaching',
  path: '/coaching',
  getParentRoute: () => PsAeWorkspaceRoute,
} as any)
const PsAeWorkspaceDashboardRoute = PsAeWorkspaceDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PsAeWorkspaceRoute,
} as any)
const PsAeWorkspaceMeetingsRoute = PsAeWorkspaceMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => PsAeWorkspaceRoute,
} as any)
const PsAeWorkspaceMyTasksRoute = PsAeWorkspaceMyTasksRouteImport.update({
  id: '/my-tasks',
  path: '/my-tasks',
  getParentRoute: () => PsAeWorkspaceRoute,
} as any)
const PsAeWorkspacePropertyInfoRoute =
  PsAeWorkspacePropertyInfoRouteImport.update({
    id: '/property-info',
    path: '/property-info',
    getParentRoute: () => PsAeWorkspaceRoute,
  } as any)
const PsAeWorkspaceSurveysRoute = PsAeWorkspaceSurveysRouteImport.update({
  id: '/surveys',
  path: '/surveys',
  getParentRoute: () => PsAeWorkspaceRoute,
} as any)
const PsContractWizardIndexRoute = PsContractWizardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PsContractWizardRoute,
} as any)
const PsContractWizardDealIdRoute = PsContractWizardDealIdRouteImport.update({
  id: '/$dealId',
  path: '/$dealId',
  getParentRoute: () => PsContractWizardRoute,
} as any)
const PsContractWizardClassicRoute = PsContractWizardClassicRouteImport.update({
  id: '/classic',
  path: '/classic',
  getParentRoute: () => PsContractWizardRoute,
} as any)
const PsContractWizardNewRoute = PsContractWizardNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PsContractWizardRoute,
} as any)
const PsTemplatesIndexRoute = PsTemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => PsRoute,
} as any)
const PsTemplatesTemplateIdRoute = PsTemplatesTemplateIdRouteImport.update({
  id: '/templates/$templateId',
  path: '/templates/$templateId',
  getParentRoute: () => PsRoute,
} as any)
const PsTemplatesAutoFieldsRoute = PsTemplatesAutoFieldsRouteImport.update({
  id: '/templates/auto-fields',
  path: '/templates/auto-fields',
  getParentRoute: () => PsRoute,
} as any)
const PsTemplatesBlockGroupsGroupIdRoute =
  PsTemplatesBlockGroupsGroupIdRouteImport.update({
    id: '/templates/block-groups/$groupId',
    path: '/templates/block-groups/$groupId',
    getParentRoute: () => PsRoute,
  } as any)
const PsTemplatesPreviewTemplateIdRoute =
  PsTemplatesPreviewTemplateIdRouteImport.update({
    id: '/templates/preview/$templateId',
    path: '/templates/preview/$templateId',
    getParentRoute: () => PsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ac': typeof AcRouteWithChildren
  '/automation': typeof AutomationRoute
  '/bd': typeof BdRouteWithChildren
  '/hotel-profile': typeof HotelProfileRoute
  '/hr': typeof HrRoute
  '/marcom': typeof MarcomRoute
  '/orm': typeof OrmRouteWithChildren
  '/ps': typeof PsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/system-cost': typeof SystemCostRoute
  '/the-office-app': typeof TheOfficeAppRouteWithChildren
  '/ac/billing': typeof AcBillingRoute
  '/ac/customers': typeof AcCustomersRoute
  '/ac/hotel-profile': typeof AcHotelProfileRoute
  '/ac/products': typeof AcProductsRoute
  '/ac/system-cost': typeof AcSystemCostRoute
  '/bd/calculator': typeof BdCalculatorRouteWithChildren
  '/bd/deals': typeof BdDealsRoute
  '/bd/quotations': typeof BdQuotationsRouteWithChildren
  '/bd/quotes': typeof BdQuotesRouteWithChildren
  '/bd/register-deal': typeof BdRegisterDealRoute
  '/l/$token': typeof LTokenRoute
  '/orm/action-a': typeof OrmActionARouteWithChildren
  '/ps/ae-workspace': typeof PsAeWorkspaceRouteWithChildren
  '/ps/contract-dashboard': typeof PsContractDashboardRoute
  '/ps/contract-wizard': typeof PsContractWizardRouteWithChildren
  '/ps/contracts': typeof PsContractsRoute
  '/ps/onboarding-process': typeof PsOnboardingProcessRoute
  '/ps/production': typeof PsProductionRoute
  '/ps/system-cost': typeof PsSystemCostRoute
  '/the-office-app/orm-bonus': typeof TheOfficeAppOrmBonusRoute
  '/ac/': typeof AcIndexRoute
  '/bd/': typeof BdIndexRoute
  '/orm/': typeof OrmIndexRoute
  '/ps/': typeof PsIndexRoute
  '/the-office-app/': typeof TheOfficeAppIndexRoute
  '/bd/calculator/marcom': typeof BdCalculatorMarcomRoute
  '/bd/calculator/orm': typeof BdCalculatorOrmRoute
  '/bd/quotations/$quoteId': typeof BdQuotationsQuoteIdRoute
  '/bd/quotes/$quoteId': typeof BdQuotesQuoteIdRoute
  '/bd/quotes/lifecycle': typeof BdQuotesLifecycleRoute
  '/orm/action-a/analysis': typeof OrmActionAAnalysisRoute
  '/orm/action-a/report': typeof OrmActionAReportRoute
  '/orm/action-a/review': typeof OrmActionAReviewRoute
  '/orm/action-a/settings': typeof OrmActionASettingsRoute
  '/ps/ae-workspace/calendar': typeof PsAeWorkspaceCalendarRoute
  '/ps/ae-workspace/coaching': typeof PsAeWorkspaceCoachingRoute
  '/ps/ae-workspace/dashboard': typeof PsAeWorkspaceDashboardRoute
  '/ps/ae-workspace/meetings': typeof PsAeWorkspaceMeetingsRoute
  '/ps/ae-workspace/my-tasks': typeof PsAeWorkspaceMyTasksRoute
  '/ps/ae-workspace/property-info': typeof PsAeWorkspacePropertyInfoRoute
  '/ps/ae-workspace/surveys': typeof PsAeWorkspaceSurveysRoute
  '/ps/contract-wizard/$dealId': typeof PsContractWizardDealIdRoute
  '/ps/contract-wizard/classic': typeof PsContractWizardClassicRoute
  '/ps/contract-wizard/new': typeof PsContractWizardNewRoute
  '/ps/templates/$templateId': typeof PsTemplatesTemplateIdRoute
  '/ps/templates/auto-fields': typeof PsTemplatesAutoFieldsRoute
  '/bd/quotations/': typeof BdQuotationsIndexRoute
  '/bd/quotes/': typeof BdQuotesIndexRoute
  '/orm/action-a/': typeof OrmActionAIndexRoute
  '/ps/ae-workspace/': typeof PsAeWorkspaceIndexRoute
  '/ps/contract-wizard/': typeof PsContractWizardIndexRoute
  '/ps/templates/': typeof PsTemplatesIndexRoute
  '/ps/templates/block-groups/$groupId': typeof PsTemplatesBlockGroupsGroupIdRoute
  '/ps/templates/preview/$templateId': typeof PsTemplatesPreviewTemplateIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/automation': typeof AutomationRoute
  '/hotel-profile': typeof HotelProfileRoute
  '/hr': typeof HrRoute
  '/marcom': typeof MarcomRoute
  '/settings': typeof SettingsRoute
  '/system-cost': typeof SystemCostRoute
  '/ac/billing': typeof AcBillingRoute
  '/ac/customers': typeof AcCustomersRoute
  '/ac/hotel-profile': typeof AcHotelProfileRoute
  '/ac/products': typeof AcProductsRoute
  '/ac/system-cost': typeof AcSystemCostRoute
  '/bd/calculator': typeof BdCalculatorRouteWithChildren
  '/bd/deals': typeof BdDealsRoute
  '/bd/register-deal': typeof BdRegisterDealRoute
  '/l/$token': typeof LTokenRoute
  '/ps/contract-dashboard': typeof PsContractDashboardRoute
  '/ps/contracts': typeof PsContractsRoute
  '/ps/onboarding-process': typeof PsOnboardingProcessRoute
  '/ps/production': typeof PsProductionRoute
  '/ps/system-cost': typeof PsSystemCostRoute
  '/the-office-app/orm-bonus': typeof TheOfficeAppOrmBonusRoute
  '/ac': typeof AcIndexRoute
  '/bd': typeof BdIndexRoute
  '/orm': typeof OrmIndexRoute
  '/ps': typeof PsIndexRoute
  '/the-office-app': typeof TheOfficeAppIndexRoute
  '/bd/calculator/marcom': typeof BdCalculatorMarcomRoute
  '/bd/calculator/orm': typeof BdCalculatorOrmRoute
  '/bd/quotations/$quoteId': typeof BdQuotationsQuoteIdRoute
  '/bd/quotes/$quoteId': typeof BdQuotesQuoteIdRoute
  '/bd/quotes/lifecycle': typeof BdQuotesLifecycleRoute
  '/orm/action-a/analysis': typeof OrmActionAAnalysisRoute
  '/orm/action-a/report': typeof OrmActionAReportRoute
  '/orm/action-a/review': typeof OrmActionAReviewRoute
  '/orm/action-a/settings': typeof OrmActionASettingsRoute
  '/ps/ae-workspace/calendar': typeof PsAeWorkspaceCalendarRoute
  '/ps/ae-workspace/coaching': typeof PsAeWorkspaceCoachingRoute
  '/ps/ae-workspace/dashboard': typeof PsAeWorkspaceDashboardRoute
  '/ps/ae-workspace/meetings': typeof PsAeWorkspaceMeetingsRoute
  '/ps/ae-workspace/my-tasks': typeof PsAeWorkspaceMyTasksRoute
  '/ps/ae-workspace/property-info': typeof PsAeWorkspacePropertyInfoRoute
  '/ps/ae-workspace/surveys': typeof PsAeWorkspaceSurveysRoute
  '/ps/contract-wizard/$dealId': typeof PsContractWizardDealIdRoute
  '/ps/contract-wizard/classic': typeof PsContractWizardClassicRoute
  '/ps/contract-wizard/new': typeof PsContractWizardNewRoute
  '/ps/templates/$templateId': typeof PsTemplatesTemplateIdRoute
  '/ps/templates/auto-fields': typeof PsTemplatesAutoFieldsRoute
  '/bd/quotations': typeof BdQuotationsIndexRoute
  '/bd/quotes': typeof BdQuotesIndexRoute
  '/orm/action-a': typeof OrmActionAIndexRoute
  '/ps/ae-workspace': typeof PsAeWorkspaceIndexRoute
  '/ps/contract-wizard': typeof PsContractWizardIndexRoute
  '/ps/templates': typeof PsTemplatesIndexRoute
  '/ps/templates/block-groups/$groupId': typeof PsTemplatesBlockGroupsGroupIdRoute
  '/ps/templates/preview/$templateId': typeof PsTemplatesPreviewTemplateIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ac': typeof AcRouteWithChildren
  '/automation': typeof AutomationRoute
  '/bd': typeof BdRouteWithChildren
  '/hotel-profile': typeof HotelProfileRoute
  '/hr': typeof HrRoute
  '/marcom': typeof MarcomRoute
  '/orm': typeof OrmRouteWithChildren
  '/ps': typeof PsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/system-cost': typeof SystemCostRoute
  '/the-office-app': typeof TheOfficeAppRouteWithChildren
  '/ac/billing': typeof AcBillingRoute
  '/ac/customers': typeof AcCustomersRoute
  '/ac/hotel-profile': typeof AcHotelProfileRoute
  '/ac/products': typeof AcProductsRoute
  '/ac/system-cost': typeof AcSystemCostRoute
  '/bd/calculator': typeof BdCalculatorRouteWithChildren
  '/bd/deals': typeof BdDealsRoute
  '/bd/quotations': typeof BdQuotationsRouteWithChildren
  '/bd/quotes': typeof BdQuotesRouteWithChildren
  '/bd/register-deal': typeof BdRegisterDealRoute
  '/l/$token': typeof LTokenRoute
  '/orm/action-a': typeof OrmActionARouteWithChildren
  '/ps/ae-workspace': typeof PsAeWorkspaceRouteWithChildren
  '/ps/contract-dashboard': typeof PsContractDashboardRoute
  '/ps/contract-wizard': typeof PsContractWizardRouteWithChildren
  '/ps/contracts': typeof PsContractsRoute
  '/ps/onboarding-process': typeof PsOnboardingProcessRoute
  '/ps/production': typeof PsProductionRoute
  '/ps/system-cost': typeof PsSystemCostRoute
  '/the-office-app/orm-bonus': typeof TheOfficeAppOrmBonusRoute
  '/ac/': typeof AcIndexRoute
  '/bd/': typeof BdIndexRoute
  '/orm/': typeof OrmIndexRoute
  '/ps/': typeof PsIndexRoute
  '/the-office-app/': typeof TheOfficeAppIndexRoute
  '/bd/calculator/marcom': typeof BdCalculatorMarcomRoute
  '/bd/calculator/orm': typeof BdCalculatorOrmRoute
  '/bd/quotations/$quoteId': typeof BdQuotationsQuoteIdRoute
  '/bd/quotes/$quoteId': typeof BdQuotesQuoteIdRoute
  '/bd/quotes/lifecycle': typeof BdQuotesLifecycleRoute
  '/orm/action-a/analysis': typeof OrmActionAAnalysisRoute
  '/orm/action-a/report': typeof OrmActionAReportRoute
  '/orm/action-a/review': typeof OrmActionAReviewRoute
  '/orm/action-a/settings': typeof OrmActionASettingsRoute
  '/ps/ae-workspace/calendar': typeof PsAeWorkspaceCalendarRoute
  '/ps/ae-workspace/coaching': typeof PsAeWorkspaceCoachingRoute
  '/ps/ae-workspace/dashboard': typeof PsAeWorkspaceDashboardRoute
  '/ps/ae-workspace/meetings': typeof PsAeWorkspaceMeetingsRoute
  '/ps/ae-workspace/my-tasks': typeof PsAeWorkspaceMyTasksRoute
  '/ps/ae-workspace/property-info': typeof PsAeWorkspacePropertyInfoRoute
  '/ps/ae-workspace/surveys': typeof PsAeWorkspaceSurveysRoute
  '/ps/contract-wizard/$dealId': typeof PsContractWizardDealIdRoute
  '/ps/contract-wizard/classic': typeof PsContractWizardClassicRoute
  '/ps/contract-wizard/new': typeof PsContractWizardNewRoute
  '/ps/templates/$templateId': typeof PsTemplatesTemplateIdRoute
  '/ps/templates/auto-fields': typeof PsTemplatesAutoFieldsRoute
  '/bd/quotations/': typeof BdQuotationsIndexRoute
  '/bd/quotes/': typeof BdQuotesIndexRoute
  '/orm/action-a/': typeof OrmActionAIndexRoute
  '/ps/ae-workspace/': typeof PsAeWorkspaceIndexRoute
  '/ps/contract-wizard/': typeof PsContractWizardIndexRoute
  '/ps/templates/': typeof PsTemplatesIndexRoute
  '/ps/templates/block-groups/$groupId': typeof PsTemplatesBlockGroupsGroupIdRoute
  '/ps/templates/preview/$templateId': typeof PsTemplatesPreviewTemplateIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ac'
    | '/automation'
    | '/bd'
    | '/hotel-profile'
    | '/hr'
    | '/marcom'
    | '/orm'
    | '/ps'
    | '/settings'
    | '/system-cost'
    | '/the-office-app'
    | '/ac/billing'
    | '/ac/customers'
    | '/ac/hotel-profile'
    | '/ac/products'
    | '/ac/system-cost'
    | '/bd/calculator'
    | '/bd/deals'
    | '/bd/quotations'
    | '/bd/quotes'
    | '/bd/register-deal'
    | '/l/$token'
    | '/orm/action-a'
    | '/ps/ae-workspace'
    | '/ps/contract-dashboard'
    | '/ps/contract-wizard'
    | '/ps/contracts'
    | '/ps/onboarding-process'
    | '/ps/production'
    | '/ps/system-cost'
    | '/the-office-app/orm-bonus'
    | '/ac/'
    | '/bd/'
    | '/orm/'
    | '/ps/'
    | '/the-office-app/'
    | '/bd/calculator/marcom'
    | '/bd/calculator/orm'
    | '/bd/quotations/$quoteId'
    | '/bd/quotes/$quoteId'
    | '/bd/quotes/lifecycle'
    | '/orm/action-a/analysis'
    | '/orm/action-a/report'
    | '/orm/action-a/review'
    | '/orm/action-a/settings'
    | '/ps/ae-workspace/calendar'
    | '/ps/ae-workspace/coaching'
    | '/ps/ae-workspace/dashboard'
    | '/ps/ae-workspace/meetings'
    | '/ps/ae-workspace/my-tasks'
    | '/ps/ae-workspace/property-info'
    | '/ps/ae-workspace/surveys'
    | '/ps/contract-wizard/$dealId'
    | '/ps/contract-wizard/classic'
    | '/ps/contract-wizard/new'
    | '/ps/templates/$templateId'
    | '/ps/templates/auto-fields'
    | '/bd/quotations/'
    | '/bd/quotes/'
    | '/orm/action-a/'
    | '/ps/ae-workspace/'
    | '/ps/contract-wizard/'
    | '/ps/templates/'
    | '/ps/templates/block-groups/$groupId'
    | '/ps/templates/preview/$templateId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/automation'
    | '/hotel-profile'
    | '/hr'
    | '/marcom'
    | '/settings'
    | '/system-cost'
    | '/ac/billing'
    | '/ac/customers'
    | '/ac/hotel-profile'
    | '/ac/products'
    | '/ac/system-cost'
    | '/bd/calculator'
    | '/bd/deals'
    | '/bd/register-deal'
    | '/l/$token'
    | '/ps/contract-dashboard'
    | '/ps/contracts'
    | '/ps/onboarding-process'
    | '/ps/production'
    | '/ps/system-cost'
    | '/the-office-app/orm-bonus'
    | '/ac'
    | '/bd'
    | '/orm'
    | '/ps'
    | '/the-office-app'
    | '/bd/calculator/marcom'
    | '/bd/calculator/orm'
    | '/bd/quotations/$quoteId'
    | '/bd/quotes/$quoteId'
    | '/bd/quotes/lifecycle'
    | '/orm/action-a/analysis'
    | '/orm/action-a/report'
    | '/orm/action-a/review'
    | '/orm/action-a/settings'
    | '/ps/ae-workspace/calendar'
    | '/ps/ae-workspace/coaching'
    | '/ps/ae-workspace/dashboard'
    | '/ps/ae-workspace/meetings'
    | '/ps/ae-workspace/my-tasks'
    | '/ps/ae-workspace/property-info'
    | '/ps/ae-workspace/surveys'
    | '/ps/contract-wizard/$dealId'
    | '/ps/contract-wizard/classic'
    | '/ps/contract-wizard/new'
    | '/ps/templates/$templateId'
    | '/ps/templates/auto-fields'
    | '/bd/quotations'
    | '/bd/quotes'
    | '/orm/action-a'
    | '/ps/ae-workspace'
    | '/ps/contract-wizard'
    | '/ps/templates'
    | '/ps/templates/block-groups/$groupId'
    | '/ps/templates/preview/$templateId'
  id:
    | '__root__'
    | '/'
    | '/ac'
    | '/automation'
    | '/bd'
    | '/hotel-profile'
    | '/hr'
    | '/marcom'
    | '/orm'
    | '/ps'
    | '/settings'
    | '/system-cost'
    | '/the-office-app'
    | '/ac/billing'
    | '/ac/customers'
    | '/ac/hotel-profile'
    | '/ac/products'
    | '/ac/system-cost'
    | '/bd/calculator'
    | '/bd/deals'
    | '/bd/quotations'
    | '/bd/quotes'
    | '/bd/register-deal'
    | '/l/$token'
    | '/orm/action-a'
    | '/ps/ae-workspace'
    | '/ps/contract-dashboard'
    | '/ps/contract-wizard'
    | '/ps/contracts'
    | '/ps/onboarding-process'
    | '/ps/production'
    | '/ps/system-cost'
    | '/the-office-app/orm-bonus'
    | '/ac/'
    | '/bd/'
    | '/orm/'
    | '/ps/'
    | '/the-office-app/'
    | '/bd/calculator/marcom'
    | '/bd/calculator/orm'
    | '/bd/quotations/$quoteId'
    | '/bd/quotes/$quoteId'
    | '/bd/quotes/lifecycle'
    | '/orm/action-a/analysis'
    | '/orm/action-a/report'
    | '/orm/action-a/review'
    | '/orm/action-a/settings'
    | '/ps/ae-workspace/calendar'
    | '/ps/ae-workspace/coaching'
    | '/ps/ae-workspace/dashboard'
    | '/ps/ae-workspace/meetings'
    | '/ps/ae-workspace/my-tasks'
    | '/ps/ae-workspace/property-info'
    | '/ps/ae-workspace/surveys'
    | '/ps/contract-wizard/$dealId'
    | '/ps/contract-wizard/classic'
    | '/ps/contract-wizard/new'
    | '/ps/templates/$templateId'
    | '/ps/templates/auto-fields'
    | '/bd/quotations/'
    | '/bd/quotes/'
    | '/orm/action-a/'
    | '/ps/ae-workspace/'
    | '/ps/contract-wizard/'
    | '/ps/templates/'
    | '/ps/templates/block-groups/$groupId'
    | '/ps/templates/preview/$templateId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcRoute: typeof AcRouteWithChildren
  AutomationRoute: typeof AutomationRoute
  BdRoute: typeof BdRouteWithChildren
  HotelProfileRoute: typeof HotelProfileRoute
  HrRoute: typeof HrRoute
  MarcomRoute: typeof MarcomRoute
  OrmRoute: typeof OrmRouteWithChildren
  PsRoute: typeof PsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SystemCostRoute: typeof SystemCostRoute
  TheOfficeAppRoute: typeof TheOfficeAppRouteWithChildren
  LTokenRoute: typeof LTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ac': {
      id: '/ac'
      path: '/ac'
      fullPath: '/ac'
      preLoaderRoute: typeof AcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation': {
      id: '/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bd': {
      id: '/bd'
      path: '/bd'
      fullPath: '/bd'
      preLoaderRoute: typeof BdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel-profile': {
      id: '/hotel-profile'
      path: '/hotel-profile'
      fullPath: '/hotel-profile'
      preLoaderRoute: typeof HotelProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr': {
      id: '/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof HrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marcom': {
      id: '/marcom'
      path: '/marcom'
      fullPath: '/marcom'
      preLoaderRoute: typeof MarcomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orm': {
      id: '/orm'
      path: '/orm'
      fullPath: '/orm'
      preLoaderRoute: typeof OrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ps': {
      id: '/ps'
      path: '/ps'
      fullPath: '/ps'
      preLoaderRoute: typeof PsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-cost': {
      id: '/system-cost'
      path: '/system-cost'
      fullPath: '/system-cost'
      preLoaderRoute: typeof SystemCostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-office-app': {
      id: '/the-office-app'
      path: '/the-office-app'
      fullPath: '/the-office-app'
      preLoaderRoute: typeof TheOfficeAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ac/': {
      id: '/ac/'
      path: '/'
      fullPath: '/ac/'
      preLoaderRoute: typeof AcIndexRouteImport
      parentRoute: typeof AcRoute
    }
    '/ac/billing': {
      id: '/ac/billing'
      path: '/billing'
      fullPath: '/ac/billing'
      preLoaderRoute: typeof AcBillingRouteImport
      parentRoute: typeof AcRoute
    }
    '/ac/customers': {
      id: '/ac/customers'
      path: '/customers'
      fullPath: '/ac/customers'
      preLoaderRoute: typeof AcCustomersRouteImport
      parentRoute: typeof AcRoute
    }
    '/ac/hotel-profile': {
      id: '/ac/hotel-profile'
      path: '/hotel-profile'
      fullPath: '/ac/hotel-profile'
      preLoaderRoute: typeof AcHotelProfileRouteImport
      parentRoute: typeof AcRoute
    }
    '/ac/products': {
      id: '/ac/products'
      path: '/products'
      fullPath: '/ac/products'
      preLoaderRoute: typeof AcProductsRouteImport
      parentRoute: typeof AcRoute
    }
    '/ac/system-cost': {
      id: '/ac/system-cost'
      path: '/system-cost'
      fullPath: '/ac/system-cost'
      preLoaderRoute: typeof AcSystemCostRouteImport
      parentRoute: typeof AcRoute
    }
    '/bd/': {
      id: '/bd/'
      path: '/'
      fullPath: '/bd/'
      preLoaderRoute: typeof BdIndexRouteImport
      parentRoute: typeof BdRoute
    }
    '/bd/calculator': {
      id: '/bd/calculator'
      path: '/calculator'
      fullPath: '/bd/calculator'
      preLoaderRoute: typeof BdCalculatorRouteImport
      parentRoute: typeof BdRoute
    }
    '/bd/deals': {
      id: '/bd/deals'
      path: '/deals'
      fullPath: '/bd/deals'
      preLoaderRoute: typeof BdDealsRouteImport
      parentRoute: typeof BdRoute
    }
    '/bd/quotations': {
      id: '/bd/quotations'
      path: '/quotations'
      fullPath: '/bd/quotations'
      preLoaderRoute: typeof BdQuotationsRouteImport
      parentRoute: typeof BdRoute
    }
    '/bd/quotes': {
      id: '/bd/quotes'
      path: '/quotes'
      fullPath: '/bd/quotes'
      preLoaderRoute: typeof BdQuotesRouteImport
      parentRoute: typeof BdRoute
    }
    '/bd/register-deal': {
      id: '/bd/register-deal'
      path: '/register-deal'
      fullPath: '/bd/register-deal'
      preLoaderRoute: typeof BdRegisterDealRouteImport
      parentRoute: typeof BdRoute
    }
    '/l/$token': {
      id: '/l/$token'
      path: '/l/$token'
      fullPath: '/l/$token'
      preLoaderRoute: typeof LTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orm/': {
      id: '/orm/'
      path: '/'
      fullPath: '/orm/'
      preLoaderRoute: typeof OrmIndexRouteImport
      parentRoute: typeof OrmRoute
    }
    '/orm/action-a': {
      id: '/orm/action-a'
      path: '/action-a'
      fullPath: '/orm/action-a'
      preLoaderRoute: typeof OrmActionARouteImport
      parentRoute: typeof OrmRoute
    }
    '/ps/': {
      id: '/ps/'
      path: '/'
      fullPath: '/ps/'
      preLoaderRoute: typeof PsIndexRouteImport
      parentRoute: typeof PsRoute
    }
    '/ps/ae-workspace': {
      id: '/ps/ae-workspace'
      path: '/ae-workspace'
      fullPath: '/ps/ae-workspace'
      preLoaderRoute: typeof PsAeWorkspaceRouteImport
      parentRoute: typeof PsRoute
    }
    '/ps/contract-dashboard': {
      id: '/ps/contract-dashboard'
      path: '/contract-dashboard'
      fullPath: '/ps/contract-dashboard'
      preLoaderRoute: typeof PsContractDashboardRouteImport
      parentRoute: typeof PsRoute
    }
    '/ps/contract-wizard': {
      id: '/ps/contract-wizard'
      path: '/contract-wizard'
      fullPath: '/ps/contract-wizard'
      preLoaderRoute: typeof PsContractWizardRouteImport
      parentRoute: typeof PsRoute
    }
    '/ps/contracts': {
      id: '/ps/contracts'
      path: '/contracts'
      fullPath: '/ps/contracts'
      preLoaderRoute: typeof PsContractsRouteImport
      parentRoute: typeof PsRoute
    }
    '/ps/onboarding-process': {
      id: '/ps/onboarding-process'
      path: '/onboarding-process'
      fullPath: '/ps/onboarding-process'
      preLoaderRoute: typeof PsOnboardingProcessRouteImport
      parentRoute: typeof PsRoute
    }
    '/ps/production': {
      id: '/ps/production'
      path: '/production'
      fullPath: '/ps/production'
      preLoaderRoute: typeof PsProductionRouteImport
      parentRoute: typeof PsRoute
    }
    '/ps/system-cost': {
      id: '/ps/system-cost'
      path: '/system-cost'
      fullPath: '/ps/system-cost'
      preLoaderRoute: typeof PsSystemCostRouteImport
      parentRoute: typeof PsRoute
    }
    '/the-office-app/': {
      id: '/the-office-app/'
      path: '/'
      fullPath: '/the-office-app/'
      preLoaderRoute: typeof TheOfficeAppIndexRouteImport
      parentRoute: typeof TheOfficeAppRoute
    }
    '/the-office-app/orm-bonus': {
      id: '/the-office-app/orm-bonus'
      path: '/orm-bonus'
      fullPath: '/the-office-app/orm-bonus'
      preLoaderRoute: typeof TheOfficeAppOrmBonusRouteImport
      parentRoute: typeof TheOfficeAppRoute
    }
    '/bd/calculator/marcom': {
      id: '/bd/calculator/marcom'
      path: '/marcom'
      fullPath: '/bd/calculator/marcom'
      preLoaderRoute: typeof BdCalculatorMarcomRouteImport
      parentRoute: typeof BdCalculatorRoute
    }
    '/bd/calculator/orm': {
      id: '/bd/calculator/orm'
      path: '/orm'
      fullPath: '/bd/calculator/orm'
      preLoaderRoute: typeof BdCalculatorOrmRouteImport
      parentRoute: typeof BdCalculatorRoute
    }
    '/bd/quotations/': {
      id: '/bd/quotations/'
      path: '/'
      fullPath: '/bd/quotations/'
      preLoaderRoute: typeof BdQuotationsIndexRouteImport
      parentRoute: typeof BdQuotationsRoute
    }
    '/bd/quotations/$quoteId': {
      id: '/bd/quotations/$quoteId'
      path: '/$quoteId'
      fullPath: '/bd/quotations/$quoteId'
      preLoaderRoute: typeof BdQuotationsQuoteIdRouteImport
      parentRoute: typeof BdQuotationsRoute
    }
    '/bd/quotes/': {
      id: '/bd/quotes/'
      path: '/'
      fullPath: '/bd/quotes/'
      preLoaderRoute: typeof BdQuotesIndexRouteImport
      parentRoute: typeof BdQuotesRoute
    }
    '/bd/quotes/$quoteId': {
      id: '/bd/quotes/$quoteId'
      path: '/$quoteId'
      fullPath: '/bd/quotes/$quoteId'
      preLoaderRoute: typeof BdQuotesQuoteIdRouteImport
      parentRoute: typeof BdQuotesRoute
    }
    '/bd/quotes/lifecycle': {
      id: '/bd/quotes/lifecycle'
      path: '/lifecycle'
      fullPath: '/bd/quotes/lifecycle'
      preLoaderRoute: typeof BdQuotesLifecycleRouteImport
      parentRoute: typeof BdQuotesRoute
    }
    '/orm/action-a/': {
      id: '/orm/action-a/'
      path: '/'
      fullPath: '/orm/action-a/'
      preLoaderRoute: typeof OrmActionAIndexRouteImport
      parentRoute: typeof OrmActionARoute
    }
    '/orm/action-a/analysis': {
      id: '/orm/action-a/analysis'
      path: '/analysis'
      fullPath: '/orm/action-a/analysis'
      preLoaderRoute: typeof OrmActionAAnalysisRouteImport
      parentRoute: typeof OrmActionARoute
    }
    '/orm/action-a/report': {
      id: '/orm/action-a/report'
      path: '/report'
      fullPath: '/orm/action-a/report'
      preLoaderRoute: typeof OrmActionAReportRouteImport
      parentRoute: typeof OrmActionARoute
    }
    '/orm/action-a/review': {
      id: '/orm/action-a/review'
      path: '/review'
      fullPath: '/orm/action-a/review'
      preLoaderRoute: typeof OrmActionAReviewRouteImport
      parentRoute: typeof OrmActionARoute
    }
    '/orm/action-a/settings': {
      id: '/orm/action-a/settings'
      path: '/settings'
      fullPath: '/orm/action-a/settings'
      preLoaderRoute: typeof OrmActionASettingsRouteImport
      parentRoute: typeof OrmActionARoute
    }
    '/ps/ae-workspace/': {
      id: '/ps/ae-workspace/'
      path: '/'
      fullPath: '/ps/ae-workspace/'
      preLoaderRoute: typeof PsAeWorkspaceIndexRouteImport
      parentRoute: typeof PsAeWorkspaceRoute
    }
    '/ps/ae-workspace/calendar': {
      id: '/ps/ae-workspace/calendar'
      path: '/calendar'
      fullPath: '/ps/ae-workspace/calendar'
      preLoaderRoute: typeof PsAeWorkspaceCalendarRouteImport
      parentRoute: typeof PsAeWorkspaceRoute
    }
    '/ps/ae-workspace/coaching': {
      id: '/ps/ae-workspace/coaching'
      path: '/coaching'
      fullPath: '/ps/ae-workspace/coaching'
      preLoaderRoute: typeof PsAeWorkspaceCoachingRouteImport
      parentRoute: typeof PsAeWorkspaceRoute
    }
    '/ps/ae-workspace/dashboard': {
      id: '/ps/ae-workspace/dashboard'
      path: '/dashboard'
      fullPath: '/ps/ae-workspace/dashboard'
      preLoaderRoute: typeof PsAeWorkspaceDashboardRouteImport
      parentRoute: typeof PsAeWorkspaceRoute
    }
    '/ps/ae-workspace/meetings': {
      id: '/ps/ae-workspace/meetings'
      path: '/meetings'
      fullPath: '/ps/ae-workspace/meetings'
      preLoaderRoute: typeof PsAeWorkspaceMeetingsRouteImport
      parentRoute: typeof PsAeWorkspaceRoute
    }
    '/ps/ae-workspace/my-tasks': {
      id: '/ps/ae-workspace/my-tasks'
      path: '/my-tasks'
      fullPath: '/ps/ae-workspace/my-tasks'
      preLoaderRoute: typeof PsAeWorkspaceMyTasksRouteImport
      parentRoute: typeof PsAeWorkspaceRoute
    }
    '/ps/ae-workspace/property-info': {
      id: '/ps/ae-workspace/property-info'
      path: '/property-info'
      fullPath: '/ps/ae-workspace/property-info'
      preLoaderRoute: typeof PsAeWorkspacePropertyInfoRouteImport
      parentRoute: typeof PsAeWorkspaceRoute
    }
    '/ps/ae-workspace/surveys': {
      id: '/ps/ae-workspace/surveys'
      path: '/surveys'
      fullPath: '/ps/ae-workspace/surveys'
      preLoaderRoute: typeof PsAeWorkspaceSurveysRouteImport
      parentRoute: typeof PsAeWorkspaceRoute
    }
    '/ps/contract-wizard/': {
      id: '/ps/contract-wizard/'
      path: '/'
      fullPath: '/ps/contract-wizard/'
      preLoaderRoute: typeof PsContractWizardIndexRouteImport
      parentRoute: typeof PsContractWizardRoute
    }
    '/ps/contract-wizard/$dealId': {
      id: '/ps/contract-wizard/$dealId'
      path: '/$dealId'
      fullPath: '/ps/contract-wizard/$dealId'
      preLoaderRoute: typeof PsContractWizardDealIdRouteImport
      parentRoute: typeof PsContractWizardRoute
    }
    '/ps/contract-wizard/classic': {
      id: '/ps/contract-wizard/classic'
      path: '/classic'
      fullPath: '/ps/contract-wizard/classic'
      preLoaderRoute: typeof PsContractWizardClassicRouteImport
      parentRoute: typeof PsContractWizardRoute
    }
    '/ps/contract-wizard/new': {
      id: '/ps/contract-wizard/new'
      path: '/new'
      fullPath: '/ps/contract-wizard/new'
      preLoaderRoute: typeof PsContractWizardNewRouteImport
      parentRoute: typeof PsContractWizardRoute
    }
    '/ps/templates/': {
      id: '/ps/templates/'
      path: '/templates'
      fullPath: '/ps/templates/'
      preLoaderRoute: typeof PsTemplatesIndexRouteImport
      parentRoute: typeof PsRoute
    }
    '/ps/templates/$templateId': {
      id: '/ps/templates/$templateId'
      path: '/templates/$templateId'
      fullPath: '/ps/templates/$templateId'
      preLoaderRoute: typeof PsTemplatesTemplateIdRouteImport
      parentRoute: typeof PsRoute
    }
    '/ps/templates/auto-fields': {
      id: '/ps/templates/auto-fields'
      path: '/templates/auto-fields'
      fullPath: '/ps/templates/auto-fields'
      preLoaderRoute: typeof PsTemplatesAutoFieldsRouteImport
      parentRoute: typeof PsRoute
    }
    '/ps/templates/block-groups/$groupId': {
      id: '/ps/templates/block-groups/$groupId'
      path: '/templates/block-groups/$groupId'
      fullPath: '/ps/templates/block-groups/$groupId'
      preLoaderRoute: typeof PsTemplatesBlockGroupsGroupIdRouteImport
      parentRoute: typeof PsRoute
    }
    '/ps/templates/preview/$templateId': {
      id: '/ps/templates/preview/$templateId'
      path: '/templates/preview/$templateId'
      fullPath: '/ps/templates/preview/$templateId'
      preLoaderRoute: typeof PsTemplatesPreviewTemplateIdRouteImport
      parentRoute: typeof PsRoute
    }
  }
}

interface AcRouteChildren {
  AcBillingRoute: typeof AcBillingRoute
  AcCustomersRoute: typeof AcCustomersRoute
  AcHotelProfileRoute: typeof AcHotelProfileRoute
  AcProductsRoute: typeof AcProductsRoute
  AcSystemCostRoute: typeof AcSystemCostRoute
  AcIndexRoute: typeof AcIndexRoute
}

const AcRouteChildren: AcRouteChildren = {
  AcBillingRoute: AcBillingRoute,
  AcCustomersRoute: AcCustomersRoute,
  AcHotelProfileRoute: AcHotelProfileRoute,
  AcProductsRoute: AcProductsRoute,
  AcSystemCostRoute: AcSystemCostRoute,
  AcIndexRoute: AcIndexRoute,
}

const AcRouteWithChildren = AcRoute._addFileChildren(AcRouteChildren)

interface BdCalculatorRouteChildren {
  BdCalculatorMarcomRoute: typeof BdCalculatorMarcomRoute
  BdCalculatorOrmRoute: typeof BdCalculatorOrmRoute
}

const BdCalculatorRouteChildren: BdCalculatorRouteChildren = {
  BdCalculatorMarcomRoute: BdCalculatorMarcomRoute,
  BdCalculatorOrmRoute: BdCalculatorOrmRoute,
}

const BdCalculatorRouteWithChildren = BdCalculatorRoute._addFileChildren(
  BdCalculatorRouteChildren,
)

interface BdQuotationsRouteChildren {
  BdQuotationsQuoteIdRoute: typeof BdQuotationsQuoteIdRoute
  BdQuotationsIndexRoute: typeof BdQuotationsIndexRoute
}

const BdQuotationsRouteChildren: BdQuotationsRouteChildren = {
  BdQuotationsQuoteIdRoute: BdQuotationsQuoteIdRoute,
  BdQuotationsIndexRoute: BdQuotationsIndexRoute,
}

const BdQuotationsRouteWithChildren = BdQuotationsRoute._addFileChildren(
  BdQuotationsRouteChildren,
)

interface BdQuotesRouteChildren {
  BdQuotesQuoteIdRoute: typeof BdQuotesQuoteIdRoute
  BdQuotesLifecycleRoute: typeof BdQuotesLifecycleRoute
  BdQuotesIndexRoute: typeof BdQuotesIndexRoute
}

const BdQuotesRouteChildren: BdQuotesRouteChildren = {
  BdQuotesQuoteIdRoute: BdQuotesQuoteIdRoute,
  BdQuotesLifecycleRoute: BdQuotesLifecycleRoute,
  BdQuotesIndexRoute: BdQuotesIndexRoute,
}

const BdQuotesRouteWithChildren = BdQuotesRoute._addFileChildren(
  BdQuotesRouteChildren,
)

interface BdRouteChildren {
  BdCalculatorRoute: typeof BdCalculatorRouteWithChildren
  BdDealsRoute: typeof BdDealsRoute
  BdQuotationsRoute: typeof BdQuotationsRouteWithChildren
  BdQuotesRoute: typeof BdQuotesRouteWithChildren
  BdRegisterDealRoute: typeof BdRegisterDealRoute
  BdIndexRoute: typeof BdIndexRoute
}

const BdRouteChildren: BdRouteChildren = {
  BdCalculatorRoute: BdCalculatorRouteWithChildren,
  BdDealsRoute: BdDealsRoute,
  BdQuotationsRoute: BdQuotationsRouteWithChildren,
  BdQuotesRoute: BdQuotesRouteWithChildren,
  BdRegisterDealRoute: BdRegisterDealRoute,
  BdIndexRoute: BdIndexRoute,
}

const BdRouteWithChildren = BdRoute._addFileChildren(BdRouteChildren)

interface OrmActionARouteChildren {
  OrmActionAAnalysisRoute: typeof OrmActionAAnalysisRoute
  OrmActionAReportRoute: typeof OrmActionAReportRoute
  OrmActionAReviewRoute: typeof OrmActionAReviewRoute
  OrmActionASettingsRoute: typeof OrmActionASettingsRoute
  OrmActionAIndexRoute: typeof OrmActionAIndexRoute
}

const OrmActionARouteChildren: OrmActionARouteChildren = {
  OrmActionAAnalysisRoute: OrmActionAAnalysisRoute,
  OrmActionAReportRoute: OrmActionAReportRoute,
  OrmActionAReviewRoute: OrmActionAReviewRoute,
  OrmActionASettingsRoute: OrmActionASettingsRoute,
  OrmActionAIndexRoute: OrmActionAIndexRoute,
}

const OrmActionARouteWithChildren = OrmActionARoute._addFileChildren(
  OrmActionARouteChildren,
)

interface OrmRouteChildren {
  OrmActionARoute: typeof OrmActionARouteWithChildren
  OrmIndexRoute: typeof OrmIndexRoute
}

const OrmRouteChildren: OrmRouteChildren = {
  OrmActionARoute: OrmActionARouteWithChildren,
  OrmIndexRoute: OrmIndexRoute,
}

const OrmRouteWithChildren = OrmRoute._addFileChildren(OrmRouteChildren)

interface PsAeWorkspaceRouteChildren {
  PsAeWorkspaceCalendarRoute: typeof PsAeWorkspaceCalendarRoute
  PsAeWorkspaceCoachingRoute: typeof PsAeWorkspaceCoachingRoute
  PsAeWorkspaceDashboardRoute: typeof PsAeWorkspaceDashboardRoute
  PsAeWorkspaceMeetingsRoute: typeof PsAeWorkspaceMeetingsRoute
  PsAeWorkspaceMyTasksRoute: typeof PsAeWorkspaceMyTasksRoute
  PsAeWorkspacePropertyInfoRoute: typeof PsAeWorkspacePropertyInfoRoute
  PsAeWorkspaceSurveysRoute: typeof PsAeWorkspaceSurveysRoute
  PsAeWorkspaceIndexRoute: typeof PsAeWorkspaceIndexRoute
}

const PsAeWorkspaceRouteChildren: PsAeWorkspaceRouteChildren = {
  PsAeWorkspaceCalendarRoute: PsAeWorkspaceCalendarRoute,
  PsAeWorkspaceCoachingRoute: PsAeWorkspaceCoachingRoute,
  PsAeWorkspaceDashboardRoute: PsAeWorkspaceDashboardRoute,
  PsAeWorkspaceMeetingsRoute: PsAeWorkspaceMeetingsRoute,
  PsAeWorkspaceMyTasksRoute: PsAeWorkspaceMyTasksRoute,
  PsAeWorkspacePropertyInfoRoute: PsAeWorkspacePropertyInfoRoute,
  PsAeWorkspaceSurveysRoute: PsAeWorkspaceSurveysRoute,
  PsAeWorkspaceIndexRoute: PsAeWorkspaceIndexRoute,
}

const PsAeWorkspaceRouteWithChildren = PsAeWorkspaceRoute._addFileChildren(
  PsAeWorkspaceRouteChildren,
)

interface PsContractWizardRouteChildren {
  PsContractWizardDealIdRoute: typeof PsContractWizardDealIdRoute
  PsContractWizardClassicRoute: typeof PsContractWizardClassicRoute
  PsContractWizardNewRoute: typeof PsContractWizardNewRoute
  PsContractWizardIndexRoute: typeof PsContractWizardIndexRoute
}

const PsContractWizardRouteChildren: PsContractWizardRouteChildren = {
  PsContractWizardDealIdRoute: PsContractWizardDealIdRoute,
  PsContractWizardClassicRoute: PsContractWizardClassicRoute,
  PsContractWizardNewRoute: PsContractWizardNewRoute,
  PsContractWizardIndexRoute: PsContractWizardIndexRoute,
}

const PsContractWizardRouteWithChildren =
  PsContractWizardRoute._addFileChildren(PsContractWizardRouteChildren)

interface PsRouteChildren {
  PsAeWorkspaceRoute: typeof PsAeWorkspaceRouteWithChildren
  PsContractDashboardRoute: typeof PsContractDashboardRoute
  PsContractWizardRoute: typeof PsContractWizardRouteWithChildren
  PsContractsRoute: typeof PsContractsRoute
  PsOnboardingProcessRoute: typeof PsOnboardingProcessRoute
  PsProductionRoute: typeof PsProductionRoute
  PsSystemCostRoute: typeof PsSystemCostRoute
  PsIndexRoute: typeof PsIndexRoute
  PsTemplatesTemplateIdRoute: typeof PsTemplatesTemplateIdRoute
  PsTemplatesAutoFieldsRoute: typeof PsTemplatesAutoFieldsRoute
  PsTemplatesIndexRoute: typeof PsTemplatesIndexRoute
  PsTemplatesBlockGroupsGroupIdRoute: typeof PsTemplatesBlockGroupsGroupIdRoute
  PsTemplatesPreviewTemplateIdRoute: typeof PsTemplatesPreviewTemplateIdRoute
}

const PsRouteChildren: PsRouteChildren = {
  PsAeWorkspaceRoute: PsAeWorkspaceRouteWithChildren,
  PsContractDashboardRoute: PsContractDashboardRoute,
  PsContractWizardRoute: PsContractWizardRouteWithChildren,
  PsContractsRoute: PsContractsRoute,
  PsOnboardingProcessRoute: PsOnboardingProcessRoute,
  PsProductionRoute: PsProductionRoute,
  PsSystemCostRoute: PsSystemCostRoute,
  PsIndexRoute: PsIndexRoute,
  PsTemplatesTemplateIdRoute: PsTemplatesTemplateIdRoute,
  PsTemplatesAutoFieldsRoute: PsTemplatesAutoFieldsRoute,
  PsTemplatesIndexRoute: PsTemplatesIndexRoute,
  PsTemplatesBlockGroupsGroupIdRoute: PsTemplatesBlockGroupsGroupIdRoute,
  PsTemplatesPreviewTemplateIdRoute: PsTemplatesPreviewTemplateIdRoute,
}

const PsRouteWithChildren = PsRoute._addFileChildren(PsRouteChildren)

interface TheOfficeAppRouteChildren {
  TheOfficeAppOrmBonusRoute: typeof TheOfficeAppOrmBonusRoute
  TheOfficeAppIndexRoute: typeof TheOfficeAppIndexRoute
}

const TheOfficeAppRouteChildren: TheOfficeAppRouteChildren = {
  TheOfficeAppOrmBonusRoute: TheOfficeAppOrmBonusRoute,
  TheOfficeAppIndexRoute: TheOfficeAppIndexRoute,
}

const TheOfficeAppRouteWithChildren = TheOfficeAppRoute._addFileChildren(
  TheOfficeAppRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcRoute: AcRouteWithChildren,
  AutomationRoute: AutomationRoute,
  BdRoute: BdRouteWithChildren,
  HotelProfileRoute: HotelProfileRoute,
  HrRoute: HrRoute,
  MarcomRoute: MarcomRoute,
  OrmRoute: OrmRouteWithChildren,
  PsRoute: PsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SystemCostRoute: SystemCostRoute,
  TheOfficeAppRoute: TheOfficeAppRouteWithChildren,
  LTokenRoute: LTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
